pr: none

variables:
  - group: JavaBuild

resources:
  repositories:
  - repository: templates
    type: github
    name: jjfood/azure-devops-pipelines
    endpoint: jjfood

stages:
  - template: builds/java-build-library.yml@templates
    parameters:
      baseVersion: '2.0'
      javaVersion: '1.8'
